#! /bin/bash

usage() {
    echo "$0 - a script to build phantomjs rpms"
    echo "Usage: $0 <spec>"
}

if [ -z "$1" ]; then
    usage
    exit 1
fi


basedir=$(cd $(dirname "$0"); pwd)
spec=$(cd $(dirname "$1"); pwd)

mkdir -p ${basedir}/{BUILD,BUILDROOT,RPMS}
rpmbuild --verbose \
    --define "_topdir ${basedir}" \
    --define "_rpmdir ${basedir}/RPMS" \
    -bb "${spec}"
