#! /bin/bash

usage() {
    echo "$0 - a script to build phantomjs rpms"
    echo "Options:"
    echo " -d - do package the rpm"
}

if [ "$1" != "-d" ]; then
    usage
    exit 1
fi

# build spec file
readonly BASEDIR=$(readlink -f $(dirname "$0"))
mkdir -p ${BASEDIR}/{BUILD,RPMS}
rpmbuild --verbose \
    --define "_topdir ${BASEDIR}" \
    -bb "${BASEDIR}/SPECS/phantomjs.spec"

